name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 100

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into Azure VM
        uses: appleboy/ssh-action@master
        env:
            COMMAND_SERVER_PORT: 9090
            QUERY_SERVER_PORT: 9090
            WORKFLOW_ENGINE_PORT: 9090
        with:
          host: ${{ secrets.AZURE_VM_HOST }} 
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
          
          script: |
            cd ./github-secrets-vm
            git pull
            echo "Successfully complete the job!"
            echo ${{ vars.COMMAND_SERVER_PORT }}
            echo ${{ vars.QUERY_SERVER_PORT }}
            echo ${{ vars.WORKFLOW_ENGINE_PORT }}

            sudo cp .env.template .env  # Copy the template file to the new file

            # Replace placeholders with specific test values
            # Replace placeholders with actual values from GitHub Secrets
            
            # Display the modified content
            cat .env

             
      - name: End JOB
        run: echo "Successfully complete the job!"
